//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace haliSatisOtomasyonu.haliSistemiWS {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="haliSistemiWS.Service1Soap")]
    public interface Service1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/kullaniciGiris", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet kullaniciGiris(string kullaniciAdi, string kullaniciKodu, string kullaniciSifre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/kullaniciGiris", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> kullaniciGirisAsync(string kullaniciAdi, string kullaniciKodu, string kullaniciSifre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/urunAra", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet urunAra(string urunAdi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/urunAra", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> urunAraAsync(string urunAdi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/satisListe", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet satisListe();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/satisListe", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> satisListeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/barcodeBilgisi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet barcodeBilgisi(string barcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/barcodeBilgisi", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> barcodeBilgisiAsync(string barcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/musteriCek", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet musteriCek();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/musteriCek", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> musteriCekAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/musteriAdiAra", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet musteriAdiAra(string musteriAdi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/musteriAdiAra", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> musteriAdiAraAsync(string musteriAdi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/musteriEkle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet musteriEkle(string musteriAdSoyad, string adres1Ulke, string adres1Sehir, string adres1Ilce, string adres1Semt, string adres1PostaKodu, string adres2Ulke, string adres2Sehir, string adres2Ilce, string adres2Semt, string adres2PostaKodu, string musteriTel1, string musteriTel2, string TCKimlikVergiNo, string vergiDairesi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/musteriEkle", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> musteriEkleAsync(string musteriAdSoyad, string adres1Ulke, string adres1Sehir, string adres1Ilce, string adres1Semt, string adres1PostaKodu, string adres2Ulke, string adres2Sehir, string adres2Ilce, string adres2Semt, string adres2PostaKodu, string musteriTel1, string musteriTel2, string TCKimlikVergiNo, string vergiDairesi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/stoklardaBarkodAra", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet stoklardaBarkodAra(string barcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/stoklardaBarkodAra", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> stoklardaBarkodAraAsync(string barcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/stoklardaUrunAdiAra", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet stoklardaUrunAdiAra(string urunAdi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/stoklardaUrunAdiAra", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> stoklardaUrunAdiAraAsync(string urunAdi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/subeStokListele", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet subeStokListele(string subeAdi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/subeStokListele", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> subeStokListeleAsync(string subeAdi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/stokHareketiAra", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet stokHareketiAra(string barcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/stokHareketiAra", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> stokHareketiAraAsync(string barcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/faturaAra", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet faturaAra(string faturaKodu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/faturaAra", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> faturaAraAsync(string faturaKodu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ayrintiliFaturaAra", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ayrintiliFaturaAra(string faturaKodu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ayrintiliFaturaAra", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ayrintiliFaturaAraAsync(string faturaKodu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/siparisEkle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet siparisEkle(string urunBarkodu, int siparisAdeti, int subeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/siparisEkle", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> siparisEkleAsync(string urunBarkodu, int siparisAdeti, int subeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/siparisListele", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet siparisListele();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/siparisListele", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> siparisListeleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/satisYap", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet satisYap(string urunBarkodu, int musteriID, int subeID, int urunMiktari);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/satisYap", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> satisYapAsync(string urunBarkodu, int musteriID, int subeID, int urunMiktari);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/faturaGoster", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet faturaGoster();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/faturaGoster", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> faturaGosterAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : haliSatisOtomasyonu.haliSistemiWS.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<haliSatisOtomasyonu.haliSistemiWS.Service1Soap>, haliSatisOtomasyonu.haliSistemiWS.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet kullaniciGiris(string kullaniciAdi, string kullaniciKodu, string kullaniciSifre) {
            return base.Channel.kullaniciGiris(kullaniciAdi, kullaniciKodu, kullaniciSifre);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> kullaniciGirisAsync(string kullaniciAdi, string kullaniciKodu, string kullaniciSifre) {
            return base.Channel.kullaniciGirisAsync(kullaniciAdi, kullaniciKodu, kullaniciSifre);
        }
        
        public System.Data.DataSet urunAra(string urunAdi) {
            return base.Channel.urunAra(urunAdi);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> urunAraAsync(string urunAdi) {
            return base.Channel.urunAraAsync(urunAdi);
        }
        
        public System.Data.DataSet satisListe() {
            return base.Channel.satisListe();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> satisListeAsync() {
            return base.Channel.satisListeAsync();
        }
        
        public System.Data.DataSet barcodeBilgisi(string barcode) {
            return base.Channel.barcodeBilgisi(barcode);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> barcodeBilgisiAsync(string barcode) {
            return base.Channel.barcodeBilgisiAsync(barcode);
        }
        
        public System.Data.DataSet musteriCek() {
            return base.Channel.musteriCek();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> musteriCekAsync() {
            return base.Channel.musteriCekAsync();
        }
        
        public System.Data.DataSet musteriAdiAra(string musteriAdi) {
            return base.Channel.musteriAdiAra(musteriAdi);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> musteriAdiAraAsync(string musteriAdi) {
            return base.Channel.musteriAdiAraAsync(musteriAdi);
        }
        
        public System.Data.DataSet musteriEkle(string musteriAdSoyad, string adres1Ulke, string adres1Sehir, string adres1Ilce, string adres1Semt, string adres1PostaKodu, string adres2Ulke, string adres2Sehir, string adres2Ilce, string adres2Semt, string adres2PostaKodu, string musteriTel1, string musteriTel2, string TCKimlikVergiNo, string vergiDairesi) {
            return base.Channel.musteriEkle(musteriAdSoyad, adres1Ulke, adres1Sehir, adres1Ilce, adres1Semt, adres1PostaKodu, adres2Ulke, adres2Sehir, adres2Ilce, adres2Semt, adres2PostaKodu, musteriTel1, musteriTel2, TCKimlikVergiNo, vergiDairesi);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> musteriEkleAsync(string musteriAdSoyad, string adres1Ulke, string adres1Sehir, string adres1Ilce, string adres1Semt, string adres1PostaKodu, string adres2Ulke, string adres2Sehir, string adres2Ilce, string adres2Semt, string adres2PostaKodu, string musteriTel1, string musteriTel2, string TCKimlikVergiNo, string vergiDairesi) {
            return base.Channel.musteriEkleAsync(musteriAdSoyad, adres1Ulke, adres1Sehir, adres1Ilce, adres1Semt, adres1PostaKodu, adres2Ulke, adres2Sehir, adres2Ilce, adres2Semt, adres2PostaKodu, musteriTel1, musteriTel2, TCKimlikVergiNo, vergiDairesi);
        }
        
        public System.Data.DataSet stoklardaBarkodAra(string barcode) {
            return base.Channel.stoklardaBarkodAra(barcode);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> stoklardaBarkodAraAsync(string barcode) {
            return base.Channel.stoklardaBarkodAraAsync(barcode);
        }
        
        public System.Data.DataSet stoklardaUrunAdiAra(string urunAdi) {
            return base.Channel.stoklardaUrunAdiAra(urunAdi);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> stoklardaUrunAdiAraAsync(string urunAdi) {
            return base.Channel.stoklardaUrunAdiAraAsync(urunAdi);
        }
        
        public System.Data.DataSet subeStokListele(string subeAdi) {
            return base.Channel.subeStokListele(subeAdi);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> subeStokListeleAsync(string subeAdi) {
            return base.Channel.subeStokListeleAsync(subeAdi);
        }
        
        public System.Data.DataSet stokHareketiAra(string barcode) {
            return base.Channel.stokHareketiAra(barcode);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> stokHareketiAraAsync(string barcode) {
            return base.Channel.stokHareketiAraAsync(barcode);
        }
        
        public System.Data.DataSet faturaAra(string faturaKodu) {
            return base.Channel.faturaAra(faturaKodu);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> faturaAraAsync(string faturaKodu) {
            return base.Channel.faturaAraAsync(faturaKodu);
        }
        
        public System.Data.DataSet ayrintiliFaturaAra(string faturaKodu) {
            return base.Channel.ayrintiliFaturaAra(faturaKodu);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ayrintiliFaturaAraAsync(string faturaKodu) {
            return base.Channel.ayrintiliFaturaAraAsync(faturaKodu);
        }
        
        public System.Data.DataSet siparisEkle(string urunBarkodu, int siparisAdeti, int subeID) {
            return base.Channel.siparisEkle(urunBarkodu, siparisAdeti, subeID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> siparisEkleAsync(string urunBarkodu, int siparisAdeti, int subeID) {
            return base.Channel.siparisEkleAsync(urunBarkodu, siparisAdeti, subeID);
        }
        
        public System.Data.DataSet siparisListele() {
            return base.Channel.siparisListele();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> siparisListeleAsync() {
            return base.Channel.siparisListeleAsync();
        }
        
        public System.Data.DataSet satisYap(string urunBarkodu, int musteriID, int subeID, int urunMiktari) {
            return base.Channel.satisYap(urunBarkodu, musteriID, subeID, urunMiktari);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> satisYapAsync(string urunBarkodu, int musteriID, int subeID, int urunMiktari) {
            return base.Channel.satisYapAsync(urunBarkodu, musteriID, subeID, urunMiktari);
        }
        
        public System.Data.DataSet faturaGoster() {
            return base.Channel.faturaGoster();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> faturaGosterAsync() {
            return base.Channel.faturaGosterAsync();
        }
    }
}
